---
- name: Install apache
  hosts: apache
  gather_facts: no
  become: yes
  vars:
    # variable to connect to remote machine after setup ssh connection
    # instead next command: ansible-playbook playbook1.yaml -l server1 --key-file ssh_key
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ ssh_keys_dir }}/{{ inventory_hostname }}_ssh_key"
  vars_files:
  - vars.yaml

  tasks:

  - name: Check/Install apache
    yum:
      name: httpd
      state: present
      update_cache: yes
    notify: start apache

  handlers:
  - name: start apache
    become: yes
    service:
      name: httpd
      state: started