---
- hosts: all
  tasks:
    - name: print msg
      debug:
        msg: Hello Ansible world

    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts['os_family']        