---
- name: First server preparation
  hosts: localhost
  gather_facts: no
  become: no
  vars:
    sshd_config_file: ./sshd_config

  tasks:

  - name: Disable root login
    lineinfile:
      path: "{{ sshd_config_file }}"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    loop:
      - { regexp: '^#PermitRootLogin', line: 'PermitRootLogin no' }
      - { regexp: '^#PermitEmptyPasswords', line: 'PermitEmptyPasswords no' } 
      - { regexp: '^#?PasswordAuthentication yes', line: 'PasswordAuthentication no' } 

#PermitRootLogin yes
#PermitEmptyPasswords yes
#PasswordAuthentication yes      