---
- name: Check/Install nginx
  become: true
  apt:
    name: nginx
    state: present
    update_cache: yes
  when: 
    - ansible_facts['distribution']|lower == "ubuntu"
  notify: restart nginx  

- name: Check/Install nginx
  become: true
  yum:
    name: nginx
    state: present
    update_cache: yes
  when: 
    - ansible_facts['distribution']|lower == "centos"      
  notify: restart nginx