---
# defaults file for init-server-preparation
local_user: dan
local_user_group: dan

ssh_key_filename: "{{inventory_hostname}}_ssh_key"
sshd_config_file: /etc/ssh/sshd_config
ssh_keys_dir: ssh_keys

vault_keys_path: ./group_vars/keys.yaml

PermitRootLogin: "PermitRootLogin no"
PasswordAuthentication: "PasswordAuthentication no"
PermitEmptyPasswords: "PermitEmptyPasswords no"


