---
- name: Generate SSH key "{{ ssh_key_filename }}"
  user:
    name: "{{ local_user }}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: "{{ssh_key_location_path}}/{{ssh_key_filename}}"
    force: no
  delegate_to: localhost
  run_once: true