---
- hosts: ubuntu
  become: true
  tasks:
  - name: create user on remote host
    ansible.builtin.user:
      name: ansible_test
      shell: /bin/bash
      group: sudo

  - name: Create a 2048-bit SSH key for user jsmith on remote host in ~jsmith/.ssh/id_rsa
    ansible.builtin.user:
      name: jsmith
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa